#!/bin/bash

IMAGE=bclapper/ebook-template
VERSION=latest

docker pull $IMAGE:$VERSION

docker run -it --rm --name ebook \
  -w /home/root/book \
  -v $(pwd):/home/root/book \
  ${IMAGE}:${VERSION} python3 ./build $@
